// TypeScript declarations for environment variables imported via '@env'
// This file tells the TypeScript compiler about the module generated by react-native-dotenv.
// Adjust the exported names if you add more variables to your .env file.

declare module '@env' {
  export const EXPO_PUBLIC_SUPABASE_URL: string;
  export const EXPO_PUBLIC_SUPABASE_ANON_KEY: string;
}
